### ISSUE TITLE
TypeError: parameter_change_mutation()

### ISSUE THREAD

**Issue by irivo** [aimclub/GOLEM#106]
After updating GOLEM to version 0.3.1,  FEDOT gives the following error:
Traceback (most recent call last):
  File "...", line 75, in <module>
    main()
  File "..", line 72, in main
    my_fedot()
  File "..", line 63, in my_fedot
    best_pipeline = model.fit(features=X_df, target=y_df)
  File "C:\..\lib\site-packages\fedot\api\main.py", line 206, in fit
    self.api_composer.obtain_model(**self.params.api_params)
  File "C:\..\lib\site-packages\fedot\api\api_utils\api_composer.py", line 82, in obtain_model
    return self.compose_fedot_model(api_params_dict, composer_params_dict, tuner_params_dict)
  File "C:\..\lib\site-packages\fedot\api\api_utils\api_composer.py", line 261, in compose_fedot_model
    best_pipeline, best_pipeline_candidates, gp_composer = self.compose_pipeline(task, train_data,
  File "C:\..\lib\site-packages\fedot\api\api_utils\api_composer.py", line 315, in compose_pipeline
    best_pipelines = gp_composer.compose_pipeline(data=train_data)
  File "C:\..\lib\site-packages\fedot\core\composer\gp_composer\gp_composer.py", line 65, in compose_pipeline
    opt_result = self.optimizer.optimise(objective_function)
  File "C:\..\lib\site-packages\golem\core\optimisers\populational_optimizer.py", line 88, in optimise
    self._initial_population(evaluator)
  File "C:\..\lib\site-packages\golem\core\optimisers\genetic\gp_optimizer.py", line 71, in _initial_population
    self.initial_individuals = self._extend_population(self.initial_individuals)
  File "C:\..\lib\site-packages\golem\core\optimisers\genetic\gp_optimizer.py", line 85, in _extend_population
    new_ind = self.mutation(choice(self.initial_individuals))
  File "C:\..\lib\site-packages\golem\core\optimisers\genetic\operators\mutation.py", line 38, in __call__
    return self._mutation(population)
  File "C:\..\lib\site-packages\golem\core\optimisers\genetic\operators\mutation.py", line 48, in _mutation
    new_graph, mutation_names = self._apply_mutations(new_graph, num_mut)
  File "C:\..\lib\site-packages\golem\core\optimisers\genetic\operators\mutation.py", line 74, in _apply_mutations
    new_graph, applied = self._adapt_and_apply_mutation(new_graph, mutation_type)
  File "C:\..\lib\site-packages\golem\core\optimisers\genetic\operators\mutation.py", line 87, in _adapt_and_apply_mutation
    new_graph = mutation_func(new_graph, requirements=self.requirements,
  File "C:\..\lib\site-packages\golem\core\adapter\adapter.py", line 173, in adapted_fun
    result = fun(*adapted_args, **adapted_kwargs)
TypeError: parameter_change_mutation() missing 2 required positional arguments: 'params' and 'opt_params'

Even such an example:
```
    model = Fedot(problem='classification') 
#------------------------------------------------------------------------------    
    best_pipeline = model.fit(features=X_df, target=y_df)
```

**Comment by gkirgizov** [comment]
Проблема на стороне FEDOT-а -- нужно поменять сигнатуру мутации. Я пофикшу.
